server:
  port: 8080
spring:
  application:
    name: "clean-architecture-hacking"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://asp-net-core-first-app-mongodb-dev:BmwdeAeARH67YJA4RR1lRMMg7EdXqogyXz7Mbj5zWVUKqchY1XOu3FXInEFyyvKviTLZqvMrTcvR2iBb0AnH7Q%3D%3D@asp-net-core-first-app-mongodb-dev.mongo.cosmos.azure.com:10255/participants?replicaSet=rs0&retryWrites=true&w=majority&maxPoolSize=15&connectTimeoutMS=30000"
#      uri: "mongodb://asp-net-core-first-app-mongodb-dev:BmwdeAeARH67YJA4RR1lRMMg7EdXqogyXz7Mbj5zWVUKqchY1XOu3FXInEFyyvKviTLZqvMrTcvR2iBb0AnH7Q%3D%3D@asp-net-core-first-app-mongodb-dev.mongo.cosmos.azure.com:10255/participants?appName=%40asp-net-core-first-app-mongodb-dev%40&authSource=admin&maxIdleTimeMS=120000&replicaSet=globaldb&retrywrites=false&ssl=true"
